[package]
name = "cli_screen_recorder"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crabgrab = { version = "0.4.0", features = ["bitmap", "screenshot"] }
ffmpeg-next = "7.1.0"
tokio = { version = "1.42.0", features = ["full"] }
